At this point we will turn our two separate projects `server` and `client` into subprojects within a Gradle multi-project build.

At the same level as the `server` and `client` directories, create a new file named `settings.gradle` and add the following content:

.settings.gradle
[source,groovy]
----
include::{sourceDir}/settings.gradle[indent=0]
----

This file will tell Gradle about the two subprojects.

Next, within the `client` directory, create a `build.gradle` file and add the following content:

.client/build.gradle
[source,groovy]
----
include::{sourceDir}/client/build.gradle[indent=0]
----

This Gradle file will install the Gradle Node plugin and configure Gradle tasks that correspond to the Yarn scripts specified in `package.json`.


We now need to add the Gradle wrapper script to our multi-project build. If you have Gradle 4.10 installed, you can generate the script using the `wrapper` command:

[source,bash]
----
~ gradle wrapper
----

TIP: Make sure to run the `wrapper` command at the same directory level as the `client` and `server` directories

Another option is to copy the wrapper scripts from the `server` directory to the directory above.

[source,bash]
----
~ cp server/gradlew .
~ cp server/gradlew.bat .
~ cp -r server/gradle/ .
----

TIP: Make sure to run the `cp` commands at the same directory level as the `client` and `server` directories


Finally, create a new `build.gradle` file (at the same level as the `settings.gradle` file created previously), and add the following content:

[source,groovy]
.build.gradle
----
include::{sourceDir}/build.gradle[indent=0]
----
<1> The `copyClientResources` task will copy the static files generated by `yarn build` into the resources directory of the `server` project.
<2> `copyClientResources` must be executed before `:server:shadowJar`. This ensures client static files will be available when the Micronaut app is assembled.
<3> The `assembleServerAndClient` task ties the copy step to the existing Gradle `shadowJar` task for the `server` project. This means that we will get our unified archive only when running this custom task (running `server:shadowJar` alone will generate a JAR file without the client resources).
