http://sendgrid.com[SendGrid] is a transactional email service.

____
SendGrid is responsible for sending billions of emails for some of the best and brightest companies in the world.
____

Add a dependency to SendGrid SDK:

[source,java]
.build.gradle
----
include::{sourceDir}/build.gradle[tag=sendgrid]
----

Create a service which encapsulates the integration with SendGrid. The bean will not be loaded if the
system properties (`sendgrid.apikey`, `sendgrid.fromemail`) or environment variables (`SENDGRID_APIKEY`, `SENDGRID_FROM_EMAIL`) are not present.

[source,java]
.src/main/java/example/micronaut/SendGridEmailCondition.java
----
include::{sourceDir}/src/main/java/example/micronaut/SendGridEmailCondition.java[]
----

Add a test:

[source,groovy]
.src/test/groovy/example/micronaut/SendGridEmailConditionSpec.groovy
----
include::{sourceDir}/src/test/groovy/example/micronaut/SendGridEmailConditionSpec.groovy[]
----

[source,java]
.src/main/java/example/micronaut/SendGridEmailService.java
----
include::{sourceDir}/src/main/java/example/micronaut/SendGridEmailService.java[]
----

<1> Use `javax.inject.Singleton` to designate a class a a singleton
<2> Bean will not loaded unless condition is met.
<3> Values will be resolved from system properties.


Add a test:

[source,groovy]
.src/test/groovy/example/micronaut/SendGridEmailServiceSpec.groovy
----
include::{sourceDir}/src/test/groovy/example/micronaut/SendGridEmailServiceSpec.groovy[]
----