include::{commondir}/common-spockinjavaapp.adoc[]

In our acceptance test, beans `SendGridEmailService` or `AwsSesMailService` will not be loaded since system properties are not present.

Instead, we setup a Mock which we can verify interactions against.

[source,groovy]
.src/test/groovy/example/micronaut/MockEmailService.groovy
----
include::{sourceDir}/src/test/groovy/example/micronaut/MockEmailService.groovy[]
----

Create the next test:

[source,groovy]
.src/test/groovy/example/micronaut/MailControllerSpec.groovy
----
include::{sourceDir}/src/test/groovy/example/micronaut/MailControllerSpec.groovy[]
----

<1> The AutoCleanup extension makes sure the `close()` method of an object (e.g. `EmbeddedServer`) is called each time a feature method is finished
<2> To run the application from a unit test you can use the http://docs.micronaut.io/snapshot/api/io/micronaut/runtime/server/EmbeddedServer.html[EmbeddedServer] interface
<3> Register a `HttpClient` bean in the application context and point it to the embedded server URL. The `EmbeddedServer` interface provides the URL of the server under test which runs on a random port.
<4> Creating HTTP Requests is easy thanks to Micronaut's fluid API.
<5> `emailService.send` method is invoked once.
